version: 0.2

env:
  variables:
    DELETE_RESOURCES: "true"

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
  build:
    commands:
      - wget https://releases.hashicorp.com/terraform/1.2.0/terraform_1.2.0_linux_amd64.zip
      - unzip terraform_1.2.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform apply -auto-approve tfplan
  post_build:
    commands:
      - |
        if [ "${DELETE_RESOURCES}" == "true" ]; then
          terraform destroy -auto-approve;
        else
          echo "Skipping resource deletion";
        fi