version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.2.0/terraform_1.2.0_linux_amd64.zip
      - unzip terraform_1.2.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan

artifacts:
  name: terraform-plan-artifact
  files:
    - '**/*'